/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "actzsxzcslalcunahhza"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdHpzeHpjc2xhbGN1bmFoaHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNjM1OTEsImV4cCI6MjA3NzgzOTU5MX0.apG-LyYfVRBzLnAdoICUuoszuJ-5nArN_O7ut6hMDUU"